# docker-compose up
version: '3.9'

services:
  node:
    build: .
    container_name: projectnode
    ports:
      - 5000:3000 # expose port 5000 to port 3000
    command: node server.js
  db:
    image: mongo
    container_name: mymongo
    ports:
      - 27017:27017
    
